- name: installing mysql client
  ansible.builtin.package:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command:  mysql -h mysql.saitejag.site -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: load sample mysql data
  ansible.builtin.shell: "mysql -h mysql.saitejag.site -uroot -p{{mysql_password}} < /app/schema/shipping.sql"
  when: schema.stdout == "0"